CREATE TABLE public.hotel (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar(50) NOT NULL,
	category int4 NOT NULL,
	CONSTRAINT hotel_pkey PRIMARY KEY (id)
);

CREATE TABLE public.availabilities (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	date DATE NULL,
	id_hotel int4 NULL,
	rooms int4 NULL,
	CONSTRAINT availabilities_pkey PRIMARY KEY (id),
	CONSTRAINT availabilities_fk FOREIGN KEY (id_hotel) REFERENCES public.hotel(id)
);

CREATE TABLE public.bookings (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	id_hotel int4 NULL,
	date_from DATE NULL,
	date_to DATE NULL,
	email varchar (100) NULL,
	CONSTRAINT bookings_pkey PRIMARY KEY (id),
	CONSTRAINT bookings_fk2 FOREIGN KEY (id_hotel) REFERENCES public.hotel(id)
);